# Qserv CI workflow
---
name: "CI"
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-run-image:
    name: Update Qserv image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 0 is "all history and branch tags"

      - name: show tag with git-describe
        run: |
          git describe --always

      - name: show ref_name
        run: echo ${{github.ref_name}}
