# Qserv CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-run-image:
    name: Update Qserv image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        run: git clone https://github.com/n8pease/qservtag.git
        # uses: actions/checkout@v3
        # with:
        #   fetch-depth: 0 # 0 is "all history and branch tags"

      - name: show tag with git-describe
        run: |
          git describe --always

      - name: show ref_name
        run: echo ${{github.ref_name}}
