# Qserv CI workflow
---
name: "CI"
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-run-image:
    name: Update Qserv image
    runs-on: ubuntu-20.04
    outputs:
      sha: ${{ steps.sha.outputs.value }}
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install click
        run: |
          python -m pip install --upgrade pip
          pip install click pyyaml requests

      - name: Checkout code
        # run: git clone https://github.com/n8pease/qservtag.git .
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 0 is "all history and branch tags"
          ref: 3c8e6c411bbdfe1bf2aa692d38cd7de422c5dbbf

      - name: Save git sha
        id: sha
        run: echo "::set-output name=value::$(git rev-parse HEAD)"

      - name: force update tags
        run: git fetch --force --tags
        # write about why this step is necessary, and include this link:
        # https://github.com/actions/checkout/issues/290

      - name: show tag with git-describe
        # run: git describe --always --tags
        run: git describe --always

      - name: show ref_name
        run: echo ${{github.ref_name}}

      - name: wait for the breaker to get checked in
        run: ./admin/local/cli/qserv wait 60

  and-then-fail:
    name: And Then Fail?
    runs-on: ubuntu-20.04
    needs: [update-run-image]
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install click
        run: |
          python -m pip install --upgrade pip
          pip install click pyyaml requests

      - name: Checkout code
        # run: git clone https://github.com/n8pease/qservtag.git .
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 0 is "all history and branch tags"
          ref: ${{ needs.update-run-image.sha }}

      - name: force update tags
        run: git fetch --force --tags
        # write about why this step is necessary, and include this link:
        # https://github.com/actions/checkout/issues/290

      - name: show tag with git-describe
        # run: git describe --always --tags
        run: git describe --always

      - name: show ref_name
        run: echo ${{github.ref_name}}
