---
name: "Tags"
on:
  push:
    tags:
      - "*"

jobs:
  show-things:
    name: show things
    runs-on: ubuntu-20.04
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install click
        run: |
          python -m pip install --upgrade pip
          pip install click pyyaml requests

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 0 is "all history and branch tags"

      - name: show tag with rev-list test
        run: |
          git describe --always

      - name: show ref_name
        run: echo ${{github.ref_name}}
